// server.ts

import express from 'express';
import bodyParser from 'body-parser';
import { RegisterRoutes } from './routes/routes'; // This is generated by TSOA

const app = express();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

RegisterRoutes(app);

export const startServer = (port: number) => {
    return new Promise((resolve, reject) => {
        app.listen(port, () => {
            console.log(`Server running on port ${port}`);
            resolve(true);
        }).on('error', (err) => {
            reject(err);
        });
    });
}
